### ISSUE TITLE
pybuilder_pytest should not run without a task

### ISSUE THREAD

**Issue by rhytnen** [AlexeySanko/pybuilder_pytest#10]
pytest runs by default but to be consistent, it should be required in the task list

**Comment by AlexeySanko** [comment]
pytest plugin is alternative for basic unittest plugin `use_plugin("python.unittest")` and uses the same task - `run_unit_tests`
Is it called without `run_unit_tests` task?

**Comment by rhytnen** [comment]
correct.  just including the plugin causes it to run regardless of whether it's in the tasklist

**Comment by AlexeySanko** [comment]
Which task do You call? `publish` task, for example, call `run_unit_tests` as dependency.

**Comment by AlexeySanko** [comment]
For example, if I call `pyb clean publish --debug`
Into output: `[DEBUG] Execution plan is clean, prepare, compile_sources, run_unit_tests, package, run_integration_tests, verify, publish`

**Comment by AlexeySanko** [comment]
If it's reason of pytest calling You can skip any task with -x argument usage:
```
-x <task>, --exclude=<task>
 +                          Exclude optional task dependencies
```
Like:
```
subprocess.check_call([build_script, "clean", "install_dependencies", "publish", "-x", "verify", "-x", "analyze",
 +                           "-x", "run_unit_tests", "-x", "run_integration_tests", "-x", "coverage"])
```
