### ISSUE TITLE
pypi 1.1.0 release is broken

### ISSUE THREAD

**Issue by docinfosci** [AlexeySanko/pybuilder_pytest#15]
Hello,

Thank you for publishing this plugin; my team and I find it to be quite helpful with our work.

Recently the package hosted on pypi was broken: inspection of pypi suggests that the package upload or definition is incomplete.  We also get this pip error on a fresh install:

    Collecting pybuilder
    Requirement already satisfied: pip>=7.1 in /Users/docinfosci/Documents/dev/skywatch/repo/microservices/aoi-workflow/lib/python3.6/site-packages (from pybuilder)
    Requirement already satisfied: wheel in /Users/docinfosci/Documents/dev/skywatch/repo/microservices/aoi-workflow/lib/python3.6/site-packages (from pybuilder)
    Requirement already satisfied: setuptools~=32.0 in /Users/docinfosci/Documents/dev/skywatch/repo/microservices/aoi-workflow/lib/python3.6/site-packages (from pybuilder)
    Collecting tblib (from pybuilder)
      Using cached tblib-1.3.2-py2.py3-none-any.whl
    Installing collected packages: tblib, pybuilder
    Successfully installed pybuilder-0.11.10 tblib-1.3.2
    PyBuilder version 0.11.10
    Build started at 2017-10-19 12:42:10
    ------------------------------------------------------------
    [WARN]  Missing plugin pypi:pybuilder_pytest
    [INFO]  Downloading plugin pypi:pybuilder_pytest
    [ERROR] The following pip error was encountered:
      Could not find a version that satisfies the requirement pybuilder_pytest (from versions: )
    No matching distribution found for pybuilder_pytest
    
    [ERROR] Could not install plugin pypi:pybuilder_pytest: Missing plugin 'pypi:pybuilder_pytest': Failed to install plugin from pybuilder_pytest.
    ------------------------------------------------------------
    BUILD FAILED - Missing plugin 'pypi:pybuilder_pytest': Failed to install plugin from pybuilder_pytest
    ------------------------------------------------------------
    Build finished at 2017-10-19 12:42:11
    Build took 0 seconds (758 ms)
    
    ----------------------------------------

Anyhow, using pip to then install this plugin from git, followed by a pip install for everything else, resolves the issue.

We would appreciate it if you would please update the pypi distribution.  If you'd like our assistance, such as for testing, please let me know.

Thanks,
Todd

**Comment by AlexeySanko** [comment]
Hi, @docinfosci 
Thanks.

Which python do You use (`python -V`)? I didn't collect WHL package for Python3 because didn't have request.

Could You please provide pip version with `pip -V`? As I understand old versions of pip don't see new packages into pypi index. :worried:
I had the same problem on old build host with pip 8.1.2 a couple days ago. Unfortuantely, I don't root rights there and just add to all build bash-scripts `pip install --upgrade --no-cache-dir pip` which force upgrade to 9.0.1 into virtual envs.

With pip 9.0.1 correctly works:
```
pip install --no-cache-dir pybuilder_pytest 
Collecting pybuilder_pytest
  Downloading pybuilder_pytest-1.1.0-py2-none-any.whl
Requirement already satisfied: pytest in ./lib/python2.7/site-packages (from pybuilder_pytest)
Requirement already satisfied: py>=1.4.33 in ./lib/python2.7/site-packages (from pytest->pybuilder_pytest)
Requirement already satisfied: setuptools in ./lib/python2.7/site-packages (from pytest->pybuilder_pytest)
Installing collected packages: pybuilder-pytest
Successfully installed pybuilder-pytest-1.1.0
```

**Comment by docinfosci** [comment]
Thanks for responding!  I apologize for the delay, lots of business travel this October.  We use Python 3.6.1 due to the target system that we deploy into.

**Comment by docinfosci** [comment]
I can provide additional context:

If I checkout the PyBuilder project and execute the build from scratch then everything works as expected with Python 3.6.1 using a virtual environment and a perfectly clean system (fresh OS, fresh pyenv, fresh Python 3.6.1, etc.).

If I reference that same PyBuilder project from another Python project using a requirements file and pip with a git+https://... reference then the build of that PyBuilder project on import fails due to the weirdness with the plugin (this is where the above error comes from).  Prior to the most recent PyPi update for this plug-in this scenario worked as expected.

Best regards,
Todd

**Comment by AlexeySanko** [comment]
Hi.
Ok, I'll fix travis.yml file today and deploy 1.1.3 for py2 and py3. Thanks

**Comment by docinfosci** [comment]
Thanks!

**Comment by AlexeySanko** [comment]
Built WHL files for Python2 and Python3 for plugins `pybuilder_pytest` version `1.1.3` and `pybuilder_pytest_coverage` version `1.1.2` on PyPi.
Thanks!

**Comment by docinfosci** [comment]
I have tested my use case with this update and found that the build now works as expected.  Thank you for your attentive help!
